function z = emptyBuffer(buffN)
%% Creates an empty Buffer of given size for storing sensor data
% Author : Kritik Soman
% Time of creation : 24 Nov 2016, 8:30pm

z=struct('x',zeros(1,buffN), ...
    'y',zeros(1,buffN),...
    'z',zeros(1,buffN),...
    't',zeros(1,buffN),...
    'N',0, ...
    'Nmax', buffN);
end